### ISSUE TITLE
手机网站支付错误

### ISSUE THREAD

**Issue by googlegame** [Nyarime/AliPayf2f-For-WHMCS#1]
手机网站支付报错, 错误代码如下:
`partner=20899999999999&res_error=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22utf-8%22%3F%3E%3Cerr%3E%3Ccode%3E0000%3C%2Fcode%3E%3Csub_code%3E0000%3C%2Fsub_code%3E%3Cmsg%3Esystem+exception%3C%2Fmsg%3E%3Cdetail%3E%E7%B3%BB%E7%BB%9F%E5%BC%82%E5%B8%B8%3C%2Fdetail%3E%3C%2Ferr%3E&service=alipay.wap.trade.create.direct`

**Comment by nyarime** [comment]
这个是在WHMCS哪个版本？可以开启debug来看是什么问题？

**Comment by nyarime** [comment]
这边测试是没有问题的，请检查对应参数是否输入错误或不符合alipay要求。

**Comment by googlegame** [comment]
WHMCS 版本 7.10.0-beta.1
当前PHP版本 7.3.20
我开启了WHMCS后台的报错，也没其他错误显示？

还有啥DEBUG方法？
我的支付宝商户也查询了，是开通了手机网站支付的
后台选择是**即时到账+手机网站支付，** 



使用电脑浏览器扫码支付没有任何错误，就是手机登录查看账单支付报如上错误，
哪后台填写的信息应该是没错的，如果有错误 电脑网站应该也无法使用
